### ISSUE TITLE
Question: Is the quantization of f32 layers that can't be converted to INT8 supported for ONNX models?

### ISSUE THREAD

**Issue by harindercnvrg** [intel/neural-compressor#598]
###yaml
```
model:
  name: bert
  framework: onnxrt_integerops
  
device: cpu

quantization:
  approach: post_training_dynamic_quant

tuning:
  accuracy_criterion:
    relative: 0.01
  exit_policy:
    timeout: 0
  random_seed: 9527
```

```
from neural_compressor.experimental import Quantization, common

onnx_output_path = "onnx/model_quantized.onnx"
quantizer = Quantization("path_to_yaml.yaml")

quantizer.model = common.Model("model.onnx")
quantizer.eval_func = functools.partial(eval_func)
quantized_model = quantizer()
```
