### ISSUE TITLE
When I use a Saved_model to do PTQ, the graph_converter.py always convert model's Input field order to random, This Caused my Dataloader to bad inputs.

### ISSUE THREAD

**Issue by GuoGuiRong** [intel/neural-compressor#65]
I have conf inputs in yaml:
```
model:                                          
  name: origin_model
  framework: tensorflow   
  inputs: dense_input,seq_50_input,sparse_ids_input,sparse_wgt_input
  outputs: dense
...
```
But the graph_converter.py always convert model's Input field order to random!!!!, SO sometime I can PQT success, sometime it caused error.

The origin saved model 's input filed order is : dense_input,seq_50_input,sparse_ids_input,sparse_wgt_input
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/22836006/160156016-1ef9e0fe-b2d3-4df7-9740-0961b630a8aa.png">
